# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f0ac9bd538fafe4c2f3cd4ca17f26069ed7cd4441e96b891dcb52d8e2e6f1db58beac63e5f79d164523a8ac9052b2af10531f28044938d162ca99382bb37898

test:
  secret_key_base: 17959c82bcc67414a0b76884eba1812191543346b2f1090a9f0bba510122b729b2483e277b19d2334195240d5edf9492a907bc6a055e51ba3a01796a4e8e7a2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
